version: "3.2"
services:
  db:
    image: postgres:9.6
    volumes:
#      - db-data:/var/lib/postgresql/data
        - db-data: C:/Program Files/PostgreSQL/9.6/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: mydb

  rabbit:
    image: rabbitmq:3-management
    expose:
      - "4369"
      - "5672"
      - "15672"
      - "25672"
    ports:
      - "5672:5672"

  publisher:
    build: ./API_service
#    environment:
#      METACIRCULARITY: 1
#      INTERVAL: 5
    command: python run_api_service.py
    entrypoint: ["./docker-entrypoint.sh"]
    links:
      - rabbit
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock


  consumer:
    build: ./api
    command: python main.py
    entrypoint: ["./docker-entrypoint.sh"]
    ports:
      - "5000:5000"
    links:
      - rabbit
      - db
    depends_on:
      - db
      - rabbit

volumes:
  db-data: